[build]
  # ビルドコマンド
  command = "npm run build"
  # ビルド成果物のディレクトリ
  publish = "dist"

[build.environment]
  # Node.jsのバージョンを指定
  NODE_VERSION = "18"

# リダイレクト設定（SPAのため）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# セキュリティヘッダーの設定
[[headers]]
  for = "/*"
  [headers.values]
    # CORS設定（RSS取得のため）
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

    # セキュリティヘッダー
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # キャッシュ設定
    Cache-Control = "public, max-age=31536000, immutable"

# 静的ファイルのキャッシュ設定
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTMLファイルはキャッシュしない
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# API プロキシ設定（外部RSSフィード用）
[[redirects]]
  from = "/api/rss/*"
  to = "https://api.allorigins.win/get?url=:splat"
  status = 200